name: Deploy Moepadata Dev Env on cPanel

on:
  push:
    branches:
      - main

jobs:
   deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: moepadata.com
          username: ${{ secrets.FTP_SUPPORT_USERNAME }}
          password: ${{ secrets.FTP_SUPPORT_PASSWORD }}
          local-dir: ./
          server-dir: /
          exclude: |
            uploads/
          log-level: verbose 